# NumPy Basics

In [1]:
import numpy as np

***
## Creating arrays

In [2]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype = float)
c = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]], dtype = int)

In [3]:
np.arange(0, 10)     # array of evenly spaced values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros((2, 3))     # array of zeros with the given shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(2)           # array of ones with the given shape

array([1., 1.])

In [6]:
np.empty((2, 3))     # empty array (arbitrary values)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.full((2, 3), 3)   # fill new array with given shape

array([[3, 3, 3],
       [3, 3, 3]])

***
## Inspecting an array

In [8]:
b.size               # number of elements in the array

10

In [9]:
b.ndim               # number of dimensions

2

In [10]:
b.shape              # lengths of each dimension

(2, 5)

In [11]:
b.dtype              # data type of array elements

dtype('float64')

***
## Basic operations

### Element-wise arithmetic

In [12]:
b + c                # element-wise addition (or np.add)

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [13]:
b - c                # element-wise subtraction (or np.subtract)

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [14]:
b * c                # element-wise multiplication (or np.multiply)

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [15]:
b / c                # element-wise division (or np.divide)

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

### Aggregation

In [16]:
b.sum()              # sum elements

45.0

In [17]:
b.min()              # minimum element

0.0

In [18]:
b.max()              # maximum element

9.0

In [19]:
b.mean()             # mean of elements

4.5

### Element-wise comparison

In [20]:
a == a               # element-wise comparison

array([ True,  True,  True,  True,  True])

In [21]:
b < 2                # element-wise comparison

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

### Array-level equality

In [22]:
np.array_equal(a, b)  # check whether arrays have the same shape and elements

False

***
## Linear algebra

In [23]:
b.T                    # reverse the array dimensions (or np.transpose)

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.],
       [4., 9.]])

In [24]:
a.dot(a)               # dot product (or np.dot)

30

In [25]:
b @ c                  # matrix multiplication (or np.matmul)

array([[ 40.,  90.],
       [115., 290.]])

In [26]:
x = c.T @ c
np.linalg.inv(x)       # matrix inverse

array([[ 0.264, -0.104],
       [-0.104,  0.044]])

In [27]:
b.trace()              # trace of a matrix

6.0

In [28]:
np.eye(3)              # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***
## Universal functions (ufuncs)

In [29]:
np.exp(a)              # exponential function

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [30]:
np.sin(a)              # sine function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [31]:
np.log(c)              # natural logarithm

array([[0.        , 1.79175947],
       [0.69314718, 1.94591015],
       [1.09861229, 2.07944154],
       [1.38629436, 2.19722458],
       [1.60943791, 2.30258509]])

In [32]:
np.abs(-b)              # absolute value

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [33]:
np.power(b, 3)          # raise to a power

array([[  0.,   1.,   8.,  27.,  64.],
       [125., 216., 343., 512., 729.]])

***
## Copying arrays

In [34]:
aa = a.copy()          # make a deep copy of the array
aa.fill(0)
print(a)
print(aa)

[0 1 2 3 4]
[0 0 0 0 0]


In [35]:
aaa = aa.view()          # create a view of the array (points to the same data in memory)
aaa.fill(1)
print(aa)
print(aaa)

[1 1 1 1 1]
[1 1 1 1 1]


***
## Array manipulation

In [36]:
b.ravel()              # flatten the array (or np.ravel)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
b.reshape(5,2)         # change shape, but don't change values

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [38]:
np.resize(b, (6,2))    # create a new array with a different shape

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.],
       [0., 1.]])

In [39]:
np.append(a, [1, 1])   # append values to the end of an array

array([0, 1, 2, 3, 4, 1, 1])

In [40]:
np.insert(a, 2, [1, 1]) # insert values at a given location

array([0, 1, 1, 1, 2, 3, 4])

In [41]:
np.delete(a, [0,2])    # delete elements at given locations

array([1, 3, 4])

In [42]:
np.concatenate((b, b+10), axis = 0)  # concatenate arrays

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [43]:
np.r_[b, b + 10]        # shorthand: concatenate arrays along their first axis (row-wise)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [44]:
np.c_[b, b + 10]        # shorthand: concatenate arrays along their second axis (column-wise)

array([[ 0.,  1.,  2.,  3.,  4., 10., 11., 12., 13., 14.],
       [ 5.,  6.,  7.,  8.,  9., 15., 16., 17., 18., 19.]])

In [45]:
np.split(b, 2, axis = 0) # split an array into sub-arrays

[array([[0., 1., 2., 3., 4.]]), array([[5., 6., 7., 8., 9.]])]

***
## Indexing/slicing

In [46]:
b[0,1]                     # select a single element (at row 0, column 1)

1.0

In [47]:
a[0:4]                     # select a slice

array([0, 1, 2, 3])

In [48]:
a[0:4:2]                   # select a slice with a stride

array([0, 2])

In [49]:
a[::-1]                    # select all elements in reverse

array([4, 3, 2, 1, 0])

In [50]:
b[:,2]                     # select all elements along the first axis (all rows) and only the elements with index 2 along the second axis

array([2., 7.])

In [51]:
a[:, np.newaxis]           # insert a new axis (here: convert a 1D array to a column vector)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [52]:
a[a>2]                     # boolean indexing

array([3, 4])